services:
  python:
    image: python:3.10
    container_name: python
    command: tail -f /dev/null
    volumes:
      - .:/app
      - python-modules:/usr/local/lib/python3.10/site-packages
    working_dir: /app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  python-modules:
  mysql-data:
